language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - PACKAGE="x509"
matrix:
  include:
  - os: linux
    env: OCAML_VERSION=4.02
  - os: linux
    env: OCAML_VERSION=4.03
  - os: linux
    env: OCAML_VERSION=4.04
  - os: linux
    env: OCAML_VERSION=4.05
  - os: linux
    env: OCAML_VERSION=4.06
  - os: osx
    env: OCAML_VERSION=4.03
notifications:
  email: false
